article/urls.py
from django.urls import path

from .views import PostList, PostDetail, Index


urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("blog/", PostList.as_view(), name="blog"),
    path("blog/<slug:slug>/", PostDetail.as_view(), name="post_detail"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("article.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("api/", include("core.urls", namespace="api"), name="api"),
    path("api-auth/", include("rest_framework.urls", namespace="rest-framework")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path, include

app_name = "api"

urlpatterns = [
    path("account/", include("account.urls_api", namespace="account")),
    path("article/", include("article.urls_api", namespace="article")),
]

article/models.py
from django.db import models
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField

from .managers import PostManager

User = get_user_model()

STATUS = (
    ("draft", "Draft"),
    ("publish", "Publish"),
)


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True)
    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(default="draft", choices=STATUS, max_length=50)

    objects = PostManager()

    class Meta:
        default_related_name = "posts"
        ordering = ("created",)

    def __str__(self) -> str:
        return self.title

    def like_count(self):
        return self.likes.count()


class Comment(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="comments")
    author = models.CharField(max_length=60)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("created",)


class Like(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="likes")
    session_key = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (("post", "session_key"),)

article/views.py
from django.db.models import Count
from django.views.generic import ListView, DetailView, TemplateView
from .models import Post

# Create your views here.


class Index(TemplateView):
    template_name="index.html"

class PostList(ListView):
    queryset = Post.objects.publish().annotate(like_count=Count("likes"))
    template_name = "blog.html"


class PostDetail(DetailView):
    model = Post
    template_name = "article.html"

    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)
        context["last_articles"] = (
            self.get_queryset().exclude(pk=self.object.pk).order_by("-created")[:3]
        )
        return context

templates/article.html
{% extends "base.html" %}
{% load static %}
{% load components %}

{% block title %}{{ object.title }}{% endblock title %}


{% block content %}
    <div class="p-4">
        <input type="hidden" id="post-id" value="{{ object.id }}"/>
        <section>
            <div class="blog-post p-5">
                <h1>{{ object.title }}</h1>
                <hr/>
                <p class="blog-post-meta text-secondary">{{ post.created|date:"d.m.Y" }} by {{ post.author }}</p>
                <p>{{ object.body|safe }}</p>
                {% like_btn %}
            </div>
        </section>

        {% include 'components/comments.html' %}

        <section class="last-articles">
            {% for last_article in last_articles %}
                <div class="card-body card">
                    <h2 class="card-title">{{ last_article.title }}</h2>
                    <p class="text-secondary">{{ last_article.created|date:"d.m.Y" }} by {{ post.author }}</p>
                    <p class="card-text">{{ last_article.body|safe|truncatewords_html:15 }}</p>
                    <a href="{% url 'post_detail' last_article.slug %}" class="btn btn-primary">Read More</a>
                </div>
            {% endfor %}
        </section>
    </div>

{% endblock content %}

templates/base.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static '/article/index.css' %}" crossorigin="anonymous" />
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand ms-5" href="/">My super blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/">Blog</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div>
        {% block content %}{% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script type="module" src="{% static '/article/script.js' %}"></script>
    {% block "script" %}{% endblock %}
</body>

</html>

templates/blog.html
{% extends "base.html" %}
{% load static %}
{% load components %}

{% block title %}Posts{% endblock title%}


{% block content %}
<div class="m-4">
  <div class="mt-4 p-5 bg-secondary text-white rounded">
    <h1 class="display-4">Hello, world!</h1>
    <p class="lead">This is a my super blog about something.</p>
  </div>
  <div class="row">
    {% for post in post_list %}
    <div class="post-item col-12 col-md-6 p-2">
      <div class="card h-100">
        <div class="card-body">
          <h2 class="card-title">{{ post.title }}</h2>
          <p class="text-secondary">{{ post.created|date:"d.m.Y" }} by {{ post.author }}</p>
          <p class="card-text">{{post.body|safe|truncatewords_html:15 }}</p>
          {% like_btn %}
          <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More</a>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
</div>
{% endblock content %}

templates/components/comments.html
<details class="comments pt-4 p-5">
    <summary>Comments</summary>
    <hr />
    <button class="btn btn-primary mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#addComments"
        aria-expanded="false" aria-controls="addComments">
        Add comment
    </button>
    <div class="collapse" id="addComments">
        <div class="card card-body mt-2">
            <form id="form-comment">
                {% csrf_token %}
                <div class="form-group">
                    <label for="author">Your name</label>
                    <input required type="text" class="form-control" id="author" name="author">
                </div>
                <div class="form-group">
                    <label for="body">Your comment</label>
                    <textarea required class="form-control" id="body" rows="3" name="body"></textarea>
                </div>
                <button class="btn btn-primary add-new" type="submit">Submit</button>
            </form>
        </div>
    </div>
    <div class="comments-list"></div>
</details>

templates/components/likeBtn.html
<button class="btn btn-primary btn-like" data-post="{{ post.id }}">
    <i class="fa fa-thumbs-up">&nbsp;Like</i>
    <span>{{ post.like_count }}</span>
</button>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load components %}

{% block title %}Posts{% endblock title%}


{% block content %}
{% include "page_blocks/bnr.html" %}
{% include "page_blocks/content.html" %}
{% endblock content %}

templates/page_blocks/bnr.html
{% load static %}

<div class="mt-4 p-5 text-black d-flex flex-column align-items-center text-center">
    <div class="info">
        <h1 class="display-4">Hello, world!</h1>
        <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    </div>
    <div class="chart">
        <object id="chart" data="{% static 'svg/chart.svg' %}" type="image/svg+xml"></object>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const obj = document.getElementById('chart')

        obj.onload = function () {
            const svgDoc = obj.contentDocument
            const path = svgDoc.querySelector('.Line')
            const length = path.getTotalLength()
            path.style.strokeDasharray = length
            path.style.strokeDashoffset = length

            gsap.to(path, {strokeDashoffset: 0, duration: 4, ease: 'power2.out'})
        }
    })
</script>

templates/page_blocks/content.html
<section class="mt-4 p-5 content">
    <article class="content_block d-flex flex-column flex-lg-row justify-content-between align-items-center">
        <div class="content_block-text">
            <h3>Lorem ipsum dolor</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi officia voluptate nulla dicta sint
                corporis animi dolorum? Deserunt modi repudiandae, accusamus repellendus, illo, eaque facere accusantium
                blanditiis nemo at tempore!
            </p>
        </div>
        <figure class="content_block-image">
            <svg id="Column Chart 1" class="column-chart" width="100%" height="100%" viewBox="0 0 1000 500"
                 xmlns="http://www.w3.org/2000/svg">
                <path
                    d="  M0,500  h66.66666666666667  v-374.2377068057993  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"></path>
                <path
                    d="  M83.33333333333333,500  h66.66666666666667  v-124.18341929261709  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"></path>
                <path
                    d="  M166.66666666666666,500  h66.66666666666667  v-241.30390507824495  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"></path>
                <path
                    d="  M250,500  h66.66666666666667  v-169.6240505642986  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"></path>
                <path
                    d="  M333.3333333333333,500  h66.66666666666667  v-306.373445924344  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"></path>
                <path
                    d="  M416.66666666666663,500  h66.66666666666667  v-260.4619243164975  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"></path>
                <path
                    d="  M500,500  h66.66666666666667  v-242.7504004591985  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"></path>
                <path
                    d="  M583.3333333333333,500  h66.66666666666667  v-241.83988197433592  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"></path>
                <path
                    d="  M666.6666666666666,500  h66.66666666666667  v-95.16828108868503  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"></path>
                <path
                    d="  M750,500  h66.66666666666667  v-294.9556406646727  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"></path>
                <path
                    d="  M833.3333333333333,500  h66.66666666666667  v-248.3089225695051  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"></path>
                <path
                    d="  M916.6666666666666,500  h66.66666666666667  v-280.4783641432936  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"></path>
            </svg>
        </figure>
    </article>
    <article class="content_block d-flex flex-column flex-lg-row justify-content-between align-items-center">
        <div class="content_block-text">
            <h3>Lorem ipsum dolor</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab quos sunt iure assumenda reprehenderit et?
                Eaque ex accusantium nisi nulla aut animi harum ad deleniti, possimus numquam laborum, corporis
                consectetur.</p>
        </div>
        <figure class="content_block-image">
            <svg id="Column Chart 2" class="column-chart" width="100%" height="100%" viewBox="0 0 1000 500"
                 xmlns="http://www.w3.org/2000/svg">
                <path
                    d="  M0,500  h66.66666666666667  v-301.37636488914677  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M83.33333333333333,500  h66.66666666666667  v-192.59522890073538  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M166.66666666666666,500  h66.66666666666667  v-189.22453492549585  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M250,500  h66.66666666666667  v-290.08247501316043  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M333.3333333333333,500  h66.66666666666667  v-399.41027490917736  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M416.66666666666663,500  h66.66666666666667  v-352.6216317157781  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M500,500  h66.66666666666667  v-178.13352150380013  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M583.3333333333333,500  h66.66666666666667  v-357.5871817402723  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M666.6666666666666,500  h66.66666666666667  v-177.73432952044004  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M750,500  h66.66666666666667  v-203.49535140823332  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M833.3333333333333,500  h66.66666666666667  v-111.67157932565794  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M916.6666666666666,500  h66.66666666666667  v-104.25353250893  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
            </svg>
        </figure>
    </article>
    <article class="content_block d-flex flex-column flex-lg-row justify-content-between align-items-center">
        <div class="content_block-text">
            <h3>Lorem ipsum dolor</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab quos sunt iure assumenda reprehenderit et?
                Eaque ex accusantium nisi nulla aut animi harum ad deleniti, possimus numquam laborum, corporis
                consectetur.</p>
        </div>
        <figure class="content_block-image">
            <svg id="Column Chart 3" class="column-chart" width="100%" height="100%" viewBox="0 0 1000 500"
                 xmlns="http://www.w3.org/2000/svg">
                <path
                    d="  M0,500  h66.66666666666667  v-95.44121017804082  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M83.33333333333333,500  h66.66666666666667  v-368.67933358608377  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M166.66666666666666,500  h66.66666666666667  v-142.84789869533734  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M250,500  h66.66666666666667  v-217.3013152562354  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M333.3333333333333,500  h66.66666666666667  v-90.87417688762923  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M416.66666666666663,500  h66.66666666666667  v-296.474727765596  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M500,500  h66.66666666666667  v-139.0299956783059  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M583.3333333333333,500  h66.66666666666667  v-244.70194224760297  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M666.6666666666666,500  h66.66666666666667  v-317.3259423207491  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M750,500  h66.66666666666667  v-354.2890346438924  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M833.3333333333333,500  h66.66666666666667  v-390.21731923238644  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M916.6666666666666,500  h66.66666666666667  v-329.6442990881289  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
            </svg>
        </figure>
    </article>
    <article class="content_block d-flex flex-column flex-lg-row justify-content-between align-items-center">
        <div class="content_block-text">
            <h3>Lorem ipsum dolor</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab quos sunt iure assumenda reprehenderit et?
                Eaque ex accusantium nisi nulla aut animi harum ad deleniti, possimus numquam laborum, corporis
                consectetur.</p>
        </div>
        <figure class="content_block-image">
            <svg id="Column Chart 4" class="column-chart" width="100%" height="100%" viewBox="0 0 1000 500"
                 xmlns="http://www.w3.org/2000/svg">
                <path
                    d="  M0,500  h66.66666666666667  v-143.24840866021646  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M83.33333333333333,500  h66.66666666666667  v-422.56418706598765  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M166.66666666666666,500  h66.66666666666667  v-361.75261458275446  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M250,500  h66.66666666666667  v-316.61320923861354  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M333.3333333333333,500  h66.66666666666667  v-288.69081545125977  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M416.66666666666663,500  h66.66666666666667  v-387.40397474664036  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M500,500  h66.66666666666667  v-247.39397678839447  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M583.3333333333333,500  h66.66666666666667  v-293.5547052516365  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M666.6666666666666,500  h66.66666666666667  v-242.6639184671244  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M750,500  h66.66666666666667  v-423.2160108414106  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M833.3333333333333,500  h66.66666666666667  v-201.8871284702284  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
                <path
                    d="  M916.6666666666666,500  h66.66666666666667  v-407.44717671913304  q0,-20 -20,-20  h-26.66666666666667  q-20,0 -20,20  Z"
                    fill="#8184c2"/>
            </svg>
        </figure>
    </article>
</section>

<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.8/ScrollMagic.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.8/plugins/animation.gsap.min.js"></script>

<script>
    const controller = new ScrollMagic.Controller()
    const columns = document.querySelectorAll('.column-chart path')

    columns.forEach(column => {
        const scene = new ScrollMagic.Scene({
            triggerElement: column,
            triggerHook: 1,
            reverse: false
        })
            .setClassToggle(column, 'animate')
            .addTo(controller)
    })
</script>